### ISSUE TITLE
Hydration free energy example request

### ISSUE THREAD

**Issue by kexul** [protocaller/ProtoCaller#6]
Hi, thanks for your great work! I'm a newbee to molecular simulation, I'm searching high-level tools through Github to perform a hydration free energy calculation. Here I found that Yank and this repo should be adequate. Would you please give a hydration free energy example? Thanks in andvance.

**Comment by miroslav351** [comment]
Hi there,

I made ProtoCaller mainly for relative binding free energies, since they are the most difficult/tedious to set up, but it is definitely possible to set up relative or absolute solvation free energy calculations from this software as well! I now uploaded a couple of examples on how to create the solvated and vacuum leg structures for both relative and absolute solvation free energy calculations. It is quite straightforward to do these, so I hope the examples shed some light on how it's done.

As for how to actually run them, I have included an example run script as well intended for binding FE calculations, which should be good for the solvation legs (with some modifications for the file names). Vacuum legs are a bit more tricky to set up, particularly since GROMACS 2020 no longer supports systems without any periodic boundary conditions. In this case, you can just create a very big box and run the same script as the solvation leg. If you have a ligand with net charge it is much more tricky to do solvation FE calculations and I am not sure on how best to run them - you will have to consult the literature for that.

In all cases, you need to analyse your energy files externally with e.g. `gmx bar`, this is not currently done within ProtoCaller and there are some nice GROMACS tutorials out there that help you with this step.

In any case if you are new to molecular simulations, I would strongly recommend familiarising yourself with the main algorithms behind free energy calculations first before running them, since there are a lot of things to look out for and even if ProtoCaller gives you an answer, it can not fix a bad input. It only takes one mistake to get a wrong free energy!

Hope that helps somewhat.

**Comment by kexul** [comment]
Thanks for your kind suggestions and honorable work!  Much appreciated!
